name: build

on:
  push:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.4"]
        cabal: [latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Set up HLint
        uses: haskell/actions/hlint-setup@v2
        with:
          version: 3.1.6
      # - name: Run HLint report
      #   uses: domdere/haskell-lint-action@v1.0.2
      - name: Run HLint
        uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
      - name: Check for Ormolu formatting
        uses: mrkkrp/ormolu-action@v7
        with:
          pattern: "**/*.hs"
      - name: Update
        run: cabal update
      - name: Build
        run: cabal build
      - name: Test
        run: cabal test
      - name: Integration Test
        run: ./test-integration/test.sh
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
